CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliveryDate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done boolean,
    projectId integer REFERENCES projects(id)
);

INSERT INTO projects(name,priority,description,deliveryDate) VALUES('Make web APP',1,'Using JS','2021-12-01');
INSERT INTO projects(name,priority,description,deliveryDate) VALUES('Make nutriologo app',2,'Using JS, react and progres','2021-12-17');
INSERT INTO projects(name,priority,description,deliveryDate) VALUES('Gestion project',3,'uppicsa','2021-12-17');

INSERT INTO tasks(name, done, projectId) VALUES('Download vuejs', false, 1);
INSERT INTO tasks(name, done, projectId) VALUES('Download react', false, 1);